teacher: "Qwen/Qwen2.5-32B-Instruct"
student: "Qwen/Qwen2.5-7B-Instruct"
precision: "bf16"
flash_attention: true
deepspeed: "configs/deepspeed_zero3.json"
train:
  epochs: 1
  lr: 2.0e-5
  grad_accum: 8
  per_device_batch: 1
  max_length: 4096
alignment:
  match_layers: "auto"     # 或显式映射: [0->0, 16->8, 32->16, 48->24, 63->31]
  loss: "mse+cosine"
data:
  sharegpt_like: false
  supervise_json_fields: ["prediction","analysis","advice"]
