model_name: "Qwen/Qwen2.5-32B-Instruct-awq"   # HuggingFace 模型名称
model_path: ""                                 # 如已下载到本地, 填写路径
hf_endpoint: ""                                # 如需访问镜像站点, 填入其 URL
engine: "vllm"                             # 使用 vLLM Offline Inference
tensor_parallel_size: 2
max_model_len: 32768
generation:
  temperature: 0.3
  top_p: 0.9
  max_new_tokens: 256
  stop: ["\n\n"]
data:
  input_jsonl: "data/processed/train.jsonl"
  output_jsonl: "data/teacher_outputs/train.pred.jsonl"
  json_schema: "json_schema/teacher_output.schema.json"
meta:
  record_sampling: true   # 保存温度/种子等采样元数据
