teachers:
  - name: deepseek
    api_key: DEEPSEEK_API_KEY
    base_url: https://api.deepseek.com
    model: deepseek-chat
  - name: qwen3
    api_key: DASHSCOPE_API_KEY
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    model: qwen-plus
  - name: gemini
    api_key: GEMINI_API_KEY
    model: gemini-2.5-flash
